evaluation:
  # Models to use
  models:
    search: ${LITELLM_SEARCH_MODEL_ID:-openrouter/google/gemini-2.0-flash-001}
    orchestrator: ${LITELLM_ORCHESTRATOR_MODEL_ID:-openrouter/google/gemini-2.0-flash-001}
    eval: ${LITELLM_EVAL_MODEL_ID:-gpt-4o-mini}
  
  # Neo4j settings for TKG
  neo4j:
    uri: ${NEO4J_URI:-bolt://localhost:7687}
    username: ${NEO4J_USERNAME:-neo4j}
    password: ${NEO4J_PASSWORD}
  
  # Test query categories
  test_queries:
    simple_factual:
      - "What is machine learning?"
      - "Who is the CEO of OpenAI?"
    
    temporal_timeline:
      - "What happened to Customer CUST001?"
      - "Show me Customer CUST003's journey"
    
    temporal_reasoning:
      - "What occurred between CUST002's signup and first support ticket?"
      - "Which customers upgraded within 30 days?"
    
    temporal_causal:
      - "What led to Customer CUST003's cancellation?"
      - "What was the sequence of events for CUST001's upgrade?"